const decors = {
	mat: [
		{
			filter: 'light',
			id: 'mat01',
			name: 'Алюминий тисненый',
			file: 'Алюминий-тисненый-300x300 1.jpg',
		},
		{
			filter: 'light',
			id: 'mat02',
			name: 'Бежевый',
			file: 'Бежевый-300x300 1.jpg',
		},
		{
			filter: 'design',
			id: 'mat03',
			name: 'Лувр',
			file: 'Лувр-298x300 1.jpg',
		},
		{
			filter: 'colors',
			id: 'mat04',
			name: 'Салатовый',
			file: 'Салатовый-300x300 1.jpg',
		},
		{
			filter: 'colors',
			id: 'mat05',
			name: 'Синий',
			file: 'Синий-300x300 1.jpg',
		},
		{
			filter: 'tree',
			id: 'mat06',
			name: 'Срез дуба',
			file: 'Срез-дуба-300x300 1.jpg',
		},
		{
			filter: 'tree',
			id: 'mat07',
			name: 'Тиковое дерево',
			file: 'Тиковое-дерево-298x300 1.jpg',
		},
		{
			filter: 'tree',
			id: 'mat08',
			name: 'Яблоня толедо',
			file: 'Яблоня-толедо-300x300 1.jpg',
		},
		{
			filter: 'dark',
			id: 'mat09',
			name: 'Венге с глубоким тиснением',
			file: 'Венге-с-глубоким-тиснением-298x300 1.jpg',
		},
		{
			filter: 'dark',
			id: 'mat10',
			name: 'Венге шоколад',
			file: 'Венге-шоколад-300x300 1.jpg',
		},
		{
			filter: 'tree',
			id: 'mat11',
			name: 'Белое дерево',
			file: 'Белое-дерево-297x300 1.jpg',
		},
		{
			filter: 'tree',
			id: 'mat12',
			name: 'Бук светлый',
			file: 'Бук-светлый-300x300 1.jpg',
		},
		{
			filter: 'tree',
			id: 'mat13',
			name: 'Бук тисненый',
			file: 'Бук-тисненый-300x300 1.jpg',
		},
		{
			filter: 'light',
			id: 'mat14',
			name: 'Белый шагрень',
			file: 'Белый-шагрень 1.jpg',
		},
		{
			filter: 'dark',
			id: 'mat15',
			name: 'Бронза',
			file: 'Бронза-300x300 1.jpg',
		},
		{
			filter: 'light',
			id: 'mat16',
			name: 'Винтаж',
			file: 'Винтаж-300x300 1.jpg',
		},
		{
			filter: 'tree',
			id: 'mat17',
			name: 'Венге',
			file: 'Венге 1.jpg',
		},
		{
			filter: 'tree',
			id: 'mat18',
			name: 'Венге',
			file: 'Венге-018-300x300 1.jpg',
		},
		{
			filter: 'tree',
			id: 'mat19',
			name: 'Венге',
			file: 'Венге-300x300 1.jpg',
		},
		{
			filter: 'tree',
			id: 'mat20',
			name: 'Венге горизонтальный',
			file: 'Венге-горизонтальный-300x300 1.jpg',
		},
		{
			filter: 'tree',
			id: 'mat21',
			name: 'Венге конго',
			file: 'Венге-конго-300x300 1.jpg',
		},
		{
			filter: 'tree',
			id: 'mat22',
			name: 'Венге премиум',
			file: 'Венге-премиум-298x300 1.jpg',
		},
		{
			filter: 'tree',
			id: 'mat23',
			name: 'Венге светлый',
			file: 'Венге-светлый-300x300 1.jpg',
		},
		{
			filter: 'tree',
			id: 'mat24',
			name: 'Венге шелк',
			file: 'Венге-шелк-300x300 1.jpg',
		},
		{
			filter: 'tree',
			id: 'mat25',
			name: 'Вишня-кальвадос',
			file: 'Вишня-кальвадос-300x300 1.jpg',
		},
		{
			filter: 'tree',
			id: 'mat26',
			name: 'Вишня мраморная',
			file: 'Вишня-мраморная-300x300 1.jpg',
		},
		{
			filter: 'tree',
			id: 'mat27',
			name: 'Вишня селекционная',
			file: 'Вишня-селекционная-300x300 1.jpg',
		},
		{
			filter: 'tree',
			id: 'mat28',
			name: 'Вишня тисненая',
			file: 'Вишня-тисненая-300x300 1.jpg',
		},
		{
			filter: 'tree',
			id: 'mat29',
			name: 'Грецкий орех',
			file: 'Грецкий-орех-300x300 1.jpg',
		},
		{
			filter: 'tree',
			id: 'mat30',
			name: 'Дуб антик',
			file: 'Дуб-антик-300x300 1.jpg',
		},
		{
			filter: 'tree',
			id: 'mat31',
			name: 'Дуб беленый',
			file: 'Дуб-беленый-300x300 1.jpg',
		},
		{
			filter: 'tree',
			id: 'mat32',
			name: 'Дуб светлый',
			file: 'Дуб-светлый-300x300 1.jpg',
		},
		{
			filter: 'tree',
			id: 'mat33',
			name: 'Дуб Турин',
			file: 'Дуб-Турин-300x300 1.jpg',
		},
		{
			filter: 'tree',
			id: 'mat34',
			name: 'Ель',
			file: 'Ель-297x300 1.jpg',
		},
		{
			filter: 'tree',
			id: 'mat35',
			name: 'Жемчужный лен',
			file: 'Жемчужный-лен-300x300 1.jpg',
		},
		{
			filter: 'tree',
			id: 'mat36',
			name: 'Золотое дерево',
			file: 'Золотое-дерево 1.jpg',
		},
		{
			filter: 'tree',
			id: 'mat37',
			name: 'Золотой ясень',
			file: 'Золотой-ясень-300x287 1.jpg',
		},
		{
			filter: 'tree',
			id: 'mat38',
			name: 'Итальянский орех',
			file: 'Итальянский-орех-300x298 1.jpg',
		},
		{
			filter: 'tree',
			id: 'mat39',
			name: 'Клен',
			file: 'Клен-300x300 1.jpg',
		},
		{
			filter: 'tree',
			id: 'mat40',
			name: 'Клен с тиснением',
			file: 'Клен-с-тиснением-300x300 1.jpg',
		},
		{
			filter: 'tree',
			id: 'mat41',
			name: 'Лён светлый',
			file: 'Лён-светлый-300x300 1.jpg',
		},
		{
			filter: 'tree',
			id: 'mat42',
			name: 'Лён тёмный',
			file: 'Лён-тёмный-300x300 1.jpg',
		},
		{
			filter: 'light',
			id: 'mat43',
			name: 'Кож.зам',
			file: 'Кож.зам 1.jpg',
		},
		{
			filter: 'dark',
			id: 'mat44',
			name: 'Коньяк',
			file: 'Коньяк-300x300 1.jpg',
		},
		{
			filter: 'light',
			id: 'mat45',
			name: 'Меланж светлый',
			file: 'Меланж-светлый-298x300 1.jpg',
		},
		{
			filter: 'dark',
			id: 'mat46',
			name: 'Меланж темный',
			file: 'Меланж-темный-300x300 1.jpg',
		},
		{
			filter: 'light',
			id: 'mat47',
			name: 'Патина премиум',
			file: 'Патина-премиум-300x300 1.jpg',
		},
		{
			filter: 'light',
			id: 'mat48',
			name: 'Перламутр горизонтальный',
			file: 'Перламутр-горизонтальный 1.jpg',
		},
		{
			filter: 'light',
			id: 'mat49',
			name: 'Серебро премиум',
			file: 'Серебро-премиум-300x300 1.jpg',
		},
		{
			filter: 'light',
			id: 'mat50',
			name: 'Слоновая кость',
			file: 'Слоновая-кость 1.jpg',
		},
		{
			filter: 'light',
			id: 'mat51',
			name: 'Прованс Версаль',
			file: 'Прованс-Версаль-300x298 1.jpg',
		},
		{
			filter: 'light',
			id: 'mat52',
			name: 'Текстиль',
			file: 'Текстиль 1.jpg',
		},
		{
			filter: 'light',
			id: 'mat53',
			name: 'Харифт',
			file: 'Харифт 1.jpg',
		},
		{
			filter: 'colors',
			id: 'mat54',
			name: 'Фисташка',
			file: 'Фисташка-300x300 1.jpg',
		},
		{
			filter: 'tree',
			id: 'mat55',
			name: 'Лесной орех',
			file: 'Лесной-орех-300x300 1.jpg',
		},
		{
			filter: 'tree',
			id: 'mat56',
			name: 'Махагон',
			file: 'Махагон-300x300 1.jpg',
		},
		{
			filter: 'tree',
			id: 'mat57',
			name: 'Ольха светлая',
			file: 'Ольха-светлая-298x300 1.jpg',
		},
		{
			filter: 'tree',
			id: 'mat58',
			name: 'Ольха тёмная',
			file: 'Ольха-тёмная-300x300 1.jpg',
		},
		{
			filter: 'tree',
			id: 'mat59',
			name: 'Орех золотой',
			file: 'Орех-золотой-300x300 1.jpg',
		},
		{
			filter: 'tree',
			id: 'mat60',
			name: 'Орех миланский',
			file: 'Орех-миланский 1.jpg',
		},
		{
			filter: 'tree',
			id: 'mat61',
			name: 'Орех-премиум',
			file: 'Орех-премиум-300x300 1.jpg',
		},
		{
			filter: 'tree',
			id: 'mat62',
			name: 'Орех тисненый',
			file: 'Орех-тисненый-300x300 1.jpg',
		},
		{
			filter: 'tree',
			id: 'mat63',
			name: 'Серое дерево',
			file: 'Серое-дерево-297x300 1.jpg',
		},
		{
			filter: 'tree',
			id: 'mat64',
			name: 'Слива',
			file: 'Слива-300x300 1.jpg',
		},
		{
			filter: 'tree',
			id: 'mat65',
			name: 'Старое-дерево',
			file: 'Старое-дерево-297x300 1.jpg',
		},
		{
			filter: 'tree',
			id: 'mat66',
			name: 'Ясень-бежевый',
			file: 'Ясень-бежевый-300x300 1.jpg',
		},
		{
			filter: 'tree',
			id: 'mat67',
			name: 'Ясень горный',
			file: 'Ясень-горный-401x400 1.jpg',
		},
		],
	metall: [
		{
			filter: 'design',
			id: 'metall01',
			name: 'Роза красная металлик',
			file: 'Роза-красная-металлик-300x207 1.jpg',
		},
		{
			filter: 'colors',
			id: 'metall02',
			name: 'Изумруд металлик',
			file: 'Изумруд-металлик-300x300 1.jpg',
		},
		{
			filter: 'colors',
			id: 'metall03',
			name: 'Красный металлик',
			file: 'Красный-металлик-297x300 1.jpg',
		},
		{
			filter: 'colors',
			id: 'metall04',
			name: 'Синий металлик',
			file: 'Синий-металлик-298x300 1.jpg',
		},
		{
			filter: 'design',
			id: 'metall05',
			name: 'Азалия металлик',
			file: 'Азалия-металлик-298x300 1.jpg',
		},
		{
			filter: 'design',
			id: 'metall06',
			name: 'Азалия фиолет металлик',
			file: 'Азалия-фиолет-металлик-300x298 1.jpg',
		},
		{
			filter: 'dark',
			id: 'metall07',
			name: 'Черный металлик',
			file: 'Черный-металлик-300x300 1.jpg',
		},
		{
			filter: 'dark',
			id: 'metall08',
			name: 'Огни Нью Йорка металлик',
			file: 'Огни-Нью-Йорка-металлик-298x300 1.jpg',
		},
		{
			filter: 'light',
			id: 'metall09',
			name: 'Белый металлик',
			file: 'Белый-металлик-300x300 1.jpg',
		},
		{
			filter: 'colors',
			id: 'metall10',
			name: 'Алый металлик',
			file: 'Алый-металлик 1.jpg',
		},
		{
			filter: 'colors',
			id: 'metall11',
			name: 'Черника металлик',
			file: 'Черника-металлик-297x300 1.jpg',
		},
		{
			filter: 'colors',
			id: 'metall12',
			name: 'Фиолетовый металлик',
			file: 'Фиолетовый-металлик 1.jpg',
		},
		{
			filter: 'colors',
			id: 'metall13',
			name: 'Сигнал оранж металлик',
			file: 'Сигнал-оранж-металлик-298x300 1.jpg',
		},
		{
			filter: 'colors',
			id: 'metall14',
			name: 'Пастель оранж-металлик',
			file: 'Пастель-оранж-металлик-296x300 1.jpg',
		},
		{
			filter: 'colors',
			id: 'metall15',
			name: 'Оранжевый металлик',
			file: 'Оранжевый-металлик-396x400 1.jpg',
		},
		{
			filter: 'colors',
			id: 'metall16',
			name: 'Бирюза металлик',
			file: 'Бирюза-металлик-300x300 1.jpg',
		},
		{
			filter: 'colors',
			id: 'metall17',
			name: 'Голубой металлик',
			file: 'Голубой-металлик-300x300 1.jpg',
		},
		{
			filter: 'colors',
			id: 'metall18',
			name: 'Лазурь металлик',
			file: 'Лазурь-металлик-300x300 1.jpg',
		},
		{
			filter: 'colors',
			id: 'metall19',
			name: 'Пурпур металлик',
			file: 'Пурпур-металлик-395x400 1.jpg',
		},
		{
			filter: 'colors',
			id: 'metall20',
			name: 'Бордо металлик',
			file: 'Бордо-металлик-300x300 1.jpg',
		},
		{
			filter: 'colors',
			id: 'metall21',
			name: 'Гламур металлик',
			file: 'Гламур-металлик-298x300 1.jpg',
		},
		{
			filter: 'colors',
			id: 'metall22',
			name: 'Салатовый металлик',
			file: 'Салатовый-металлик-293x300 1.jpg',
		},
		{
			filter: 'colors',
			id: 'metall23',
			name: 'Олива металлик металлик',
			file: 'Олива-металлик-металлик-300x300 1.jpg',
		},
		{
			filter: 'light',
			id: 'metall24',
			name: 'Пастель фиолет',
			file: 'Пастель-фиолет-металлик-300x300 1.jpg',
		},
		{
			filter: 'light',
			id: 'metall25',
			name: 'Розовый металлик',
			file: 'Розовый-металлик-300x300 1.jpg',
		},
		{
			filter: 'light',
			id: 'metall26',
			name: 'Светло желтый металлик',
			file: 'Светло-желтый-металлик-300x300 1.jpg',
		},
		{
			filter: 'light',
			id: 'metall27',
			name: 'Серебряный дождь металлик',
			file: 'Серебряный-дождь-металлик-300x297 1.jpg',
		},
		{
			filter: 'dark',
			id: 'metall28',
			name: 'Мокрый песок металлик',
			file: 'Мокрый-песок-металлик-300x300 1.jpg',
		},
		{
			filter: 'dark',
			id: 'metall29',
			name: 'Серебристый металлик',
			file: 'Серебристый-металлик-298x300 1.jpg',
		},
		],
	gloss: [
		{
			filter: 'design',
			id: 'gloss01',
			name: 'Зефир',
			file: 'Зефир-300x300 1.jpg',
		},
		{
			filter: 'dark',
			id: 'gloss02',
			name: 'Багира глянец',
			file: 'Багира-глянец-300x300 1.jpg',
		},
		{
			filter: 'dark',
			id: 'gloss03',
			name: 'Черный Глянцевый',
			file: 'Черный-Глянцевый-300x300 1.jpg',
		},
		{
			filter: 'dark',
			id: 'gloss04',
			name: 'Черный Страйп',
			file: 'Черный-Страйп-300x297 1.jpg',
		},
		{
			filter: 'colors',
			id: 'gloss05',
			name: 'Аквамарин глянец',
			file: 'Аквамарин-глянец-300x300 1.jpg',
		},
		{
			filter: 'colors',
			id: 'gloss06',
			name: 'Бордо глянец',
			file: 'Бордо-глянец-296x300 1.jpg',
		},
		{
			filter: 'tree',
			id: 'gloss07',
			name: 'Вишня глянец',
			file: 'Вишня-глянец-300x300 1.jpg',
		},
		{
			filter: 'tree',
			id: 'gloss08',
			name: 'Кедр глянец',
			file: 'Кедр-глянец-300x300 1.jpg',
		},
		{
			filter: 'tree',
			id: 'gloss09',
			name: 'Ольха светлая глянец',
			file: 'Ольха-светлая-глянец-300x300 1.jpg',
		},
		{
			filter: 'tree',
			id: 'gloss10',
			name: 'Ольха тёмная глянец',
			file: 'Ольха-тёмная-глянец-300x300 1.jpg',
		},
		{
			filter: 'tree',
			id: 'gloss11',
			name: 'Венге Глянец',
			file: 'Венге-Глянец-297x300 1.jpg',
		},
		{
			filter: 'light',
			id: 'gloss12',
			name: 'Белый Глянцевый',
			file: 'Белый-Глянцевый-298x300 1.jpg',
		},
		{
			filter: 'light',
			id: 'gloss13',
			name: 'Белый Страйп',
			file: 'Белый-Страйп-297x300 1.jpg',
		},
		{
			filter: 'light',
			id: 'gloss14',
			name: 'Снежный барс глянец',
			file: 'Снежный-барс-глянец-298x300 1.jpg',
		},
		{
			filter: 'light',
			id: 'gloss15',
			name: 'Бежевый перламутр глянец',
			file: 'Бежевый-перламутр-глянец-300x300 1.jpg',
		},
		{
			filter: 'light',
			id: 'gloss16',
			name: 'Ваниль Глянец',
			file: 'Ваниль-Глянец-300x298 1.jpg',
		},
		{
			filter: 'light',
			id: 'gloss17',
			name: 'Мокко глянец',
			file: 'Мокко-глянец-300x300 1.jpg',
		},
		{
			filter: 'colors',
			id: 'gloss18',
			name: 'Манго Глянец',
			file: 'Манго-Глянец-300x300 1.jpg',
		},
		{
			filter: 'colors',
			id: 'gloss19',
			name: 'Олива глянец',
			file: 'Олива-глянец-298x300 1.jpg',
		},
		{
			filter: 'colors',
			id: 'gloss20',
			name: 'Эвкалипт Глянец',
			file: 'Эвкалипт-Глянец-300x300 1.jpg',
		},
		{
			filter: 'dark',
			id: 'gloss21',
			name: 'Шоколад глянец',
			file: 'Шоколад-глянец-300x300 1.jpg',
		},
		{
			filter: 'dark',
			id: 'gloss22',
			name: 'Тигровый глаз глянец',
			file: 'Тигровый-глаз-глянец-300x300 1.jpg',
		},
		{
			filter: 'dark',
			id: 'gloss23',
			name: 'Капучино глянец',
			file: 'Капучино-глянец-300x300 1.jpg',
		},
		],
	ldsp: [
		{
			filter: 'colors',
			id: 'ldsp01',
			name: 'Голубой',
			file: 'Голубой 1.jpg',
		},
		{
			filter: 'colors',
			id: 'ldsp02',
			name: 'Фисташковый',
			file: 'Фисташковый 1.jpg',
		},
		{
			filter: 'colors',
			id: 'ldsp03',
			name: 'Салатовый',
			file: 'Салатовый 1.jpg',
		},
		{
			filter: 'colors',
			id: 'ldsp04',
			name: 'Светло синий',
			file: 'Светло-синий 1.jpg',
		},
		{
			filter: 'dark',
			id: 'ldsp05',
			name: 'Уни нерро',
			file: 'Уни-нерро 1.jpg',
		},
		{
			filter: 'dark',
			id: 'ldsp06',
			name: 'Серый',
			file: 'Серый 1.jpg',
		},
		{
			filter: 'colors',
			id: 'ldsp07',
			name: 'Красный',
			file: 'Красный 1.jpg',
		},
		{
			filter: 'dark',
			id: 'ldsp08',
			name: 'Алюминий',
			file: 'Алюминий 1.jpg',
		},
		{
			filter: 'tree',
			id: 'ldsp09',
			name: 'Аруба венге',
			file: 'Аруба-венге 1.jpg',
		},
		{
			filter: 'tree',
			id: 'ldsp10',
			name: 'Бук бавария 55',
			file: 'Бук-бавария-55 1.jpg',
		},
		{
			filter: 'tree',
			id: 'ldsp11',
			name: 'Бук бавария 109',
			file: 'Бук-бавария-109 1.jpg',
		},
		{
			filter: 'tree',
			id: 'ldsp12',
			name: 'Бук натуральный',
			file: 'Бук-натуральный 1.jpg',
		},
		{
			filter: 'tree',
			id: 'ldsp13',
			name: 'Бук невский',
			file: 'Бук-невский 1.jpg',
		},
		{
			filter: 'tree',
			id: 'ldsp14',
			name: 'Венге Конго',
			file: 'Венге-Конго 1.jpg',
		},
		{
			filter: 'tree',
			id: 'ldsp15',
			name: 'Дуб баррик темный',
			file: 'Дуб-баррик-темный 1.jpg',
		},
		{
			filter: 'light',
			id: 'ldsp16',
			name: 'Бежевый',
			file: 'Бежевый 1.jpg',
		},
		{
			filter: 'light',
			id: 'ldsp17',
			name: 'Белый',
			file: 'Белый 1.jpg',
		},
		{
			filter: 'light',
			id: 'ldsp18',
			name: 'Крем',
			file: 'Крем 1.jpg',
		},
		{
			filter: 'light',
			id: 'ldsp19',
			name: 'Уни металлик',
			file: 'Уни-металлик 1.jpg',
		},
		{
			filter: 'light',
			id: 'ldsp20',
			name: 'Венге светлый',
			file: 'Венге-светлый 1.jpg',
		},
		{
			filter: 'light',
			id: 'ldsp21',
			name: 'Дуб атланта',
			file: 'Дуб-атланта 1.jpg',
		},
		{
			filter: 'light',
			id: 'ldsp22',
			name: 'Дуб млечный',
			file: 'Дуб-млечный 1.jpg',
		},
		{
			filter: 'light',
			id: 'ldsp23',
			name: 'Дуб паллада',
			file: 'Дуб-паллада 1.jpg',
		},
		{
			filter: 'light',
			id: 'ldsp24',
			name: 'Дуб сонома',
			file: 'Дуб-сонома 1.jpg',
		},
		{
			filter: 'light',
			id: 'ldsp25',
			name: 'Дуб французкий',
			file: 'Дуб-французкий 1.jpg',
		},
		{
			filter: 'light',
			id: 'ldsp26',
			name: 'Клен танзау',
			file: 'Клен-танзау 1.jpg',
		},
		{
			filter: 'light',
			id: 'ldsp27',
			name: 'Ясень шимо светлый',
			file: 'Ясень-шимо-светлый 1.jpg',
		},
		{
			filter: 'light',
			id: 'ldsp28',
			name: 'Дуб баррик светлый',
			file: 'Дуб-баррик-светлый 1.jpg',
		},
		{
			filter: 'light',
			id: 'ldsp29',
			name: 'Ноче Ногаро светлый',
			file: 'Ноче-Ногаро-светлый 1.jpg',
		},
		{
			filter: 'tree',
			id: 'ldsp30',
			name: 'Вишня академия',
			file: 'Вишня-академия 1.jpg',
		},
		{
			filter: 'tree',
			id: 'ldsp31',
			name: 'Вишня оксфорд',
			file: 'Вишня-оксфорд 1.jpg',
		},
		{
			filter: 'tree',
			id: 'ldsp32',
			name: 'Дуб арденский',
			file: 'Дуб-арденский 1.jpg',
		},
		{
			filter: 'tree',
			id: 'ldsp33',
			name: 'Дуб гауди',
			file: 'Дуб-гауди 1.jpg',
		},
		{
			filter: 'tree',
			id: 'ldsp34',
			name: 'Вишня академия',
			file: 'Вишня-академия 1.jpg',
		},
		{
			filter: 'tree',
			id: 'ldsp35',
			name: 'Ноче Гварнери',
			file: 'Ноче-Гварнери 1.jpg',
		},
		{
			filter: 'dark',
			id: 'ldsp36',
			name: 'Линум Венге',
			file: 'Линум-Венге 1.jpg',
		},
		{
			filter: 'dark',
			id: 'ldsp37',
			name: 'Махагон',
			file: 'Махагон 1.jpg',
		},
		{
			filter: 'tree',
			id: 'ldsp38',
			name: 'Ноче Мария Луиза',
			file: 'Ноче-Мария-Луиза 1.jpg',
		},
		{
			filter: 'tree',
			id: 'ldsp39',
			name: 'Ноче Ногаро темный',
			file: 'Ноче-Ногаро-темный 1.jpg',
		},
		{
			filter: 'tree',
			id: 'ldsp40',
			name: 'Ноче экко',
			file: 'Ноче-экко 1.jpg',
		},
		{
			filter: 'tree',
			id: 'ldsp41',
			name: 'Ольха 40',
			file: 'Ольха-40 1.jpg',
		},
		{
			filter: 'tree',
			id: 'ldsp42',
			name: 'Ольха 75',
			file: 'Ольха-75 1.jpg',
		},
		{
			filter: 'tree',
			id: 'ldsp43',
			name: 'Орех донской',
			file: 'Орех-донской 1.jpg',
		},
		{
			filter: 'tree',
			id: 'ldsp44',
			name: 'Орех испанский',
			file: 'Орех-испанский 1.jpg',
		},
		{
			filter: 'tree',
			id: 'ldsp45',
			name: 'Орех миланский',
			file: 'Орех-миланский 2.jpg',
		},
		{
			filter: 'tree',
			id: 'ldsp46',
			name: 'Слива-валлис',
			file: 'Слива-валлис 1.jpg',
		},
		{
			filter: 'tree',
			id: 'ldsp47',
			name: 'Яблоня локарно',
			file: 'Яблоня-локарно 1.jpg',
		},
		{
			filter: 'tree',
			id: 'ldsp48',
			name: 'Ясень шимо темный',
			file: 'Ясень-шимо-темный 1.jpg',
		},
		],
	arpa: [
		{
			filter: 'eree',
			id: 'arpa01',
			name: 'arpa 0709 erre',
			file: '0709_erre 1.jpg',
		},
		{
			filter: 'eree',
			id: 'arpa02',
			name: 'arpa 0700 erre',
			file: '0700_erre 1.jpg',
		},
		{
			filter: 'eree',
			id: 'arpa03',
			name: 'arpa 0509 erre',
			file: '0509_erre 1.jpg',
		},
		{
			filter: 'aleve',
			id: 'arpa04',
			name: 'arpa 4512 aleve',
			file: '4512_aleve 1.jpg',
		},
		{
			filter: 'aleve',
			id: 'arpa05',
			name: 'arpa 4412 aleve',
			file: '4412_erre 1.jpg',
		},
		{
			filter: 'aleve',
			id: 'arpa06',
			name: 'arpa 4536 aleve',
			file: '4536_aleve 1.jpg',
		},
	],
	marshall: [
		{
			filter: 'texture',
			id: 'marshall01',
			name: '200FT',
			file: '200FT 1.jpg',
		},
		{
			filter: 'texture',
			id: 'marshall02',
			name: '400FT',
			file: '400FT 1.jpg',
		},
		{
			filter: 'texture',
			id: 'marshall03',
			name: '200ZT',
			file: '200ZT 1.jpg',
		},
		{
			filter: 'texture',
			id: 'marshall04',
			name: '400ZT',
			file: '400ZT 1.jpg',
		},
		{
			filter: 'texture',
			id: 'marshall05',
			name: '400POG',
			file: '400POG 1.jpg',
		},
		{
			filter: 'texture',
			id: 'marshall06',
			name: '1176BG',
			file: '1176BG 1.jpg',
		},
		{
			filter: 'woody',
			id: 'marshall07',
			name: '1179BG',
			file: '1179BG 1.jpg',
		},
		{
			filter: 'woody',
			id: 'marshall08',
			name: '1196BG',
			file: '1196BG 1.jpg',
		},
		{
			filter: 'woody',
			id: 'marshall09',
			name: '1799AG',
			file: '1799AG 1.jpg',
		},
		{
			filter: 'woody',
			id: 'marshall10',
			name: '1169ACT',
			file: '1169ACT 1.jpg',
		},
		{
			filter: 'monotone',
			id: 'marshall11',
			name: '2761G',
			file: '2761G 1.jpg',
		},
		{
			filter: 'monotone',
			id: 'marshall12',
			name: '2760AG',
			file: '2760AG 1.jpg',
		},
		{
			filter: 'monotone',
			id: 'marshall13',
			name: '2759AG',
			file: '2759AG 1.jpg',
		},
		{
			filter: 'monotone',
			id: 'marshall14',
			name: '2757AG',
			file: '2757AG 1.jpg',
		},
		{
			filter: 'monotone',
			id: 'marshall15',
			name: '2755AG',
			file: '2755AG 1.jpg',
		},
		{
			filter: 'monotone',
			id: 'marshall16',
			name: '2751AG',
			file: '2751AG 1.jpg',
		},
		{
			filter: 'monotone',
			id: 'marshall17',
			name: '2745DG',
			file: '2745DG 1.jpg',
		},
		{
			filter: 'monotone',
			id: 'marshall18',
			name: '60G',
			file: '60G 1.jpg',
		},
		{
			filter: 'monotone',
			id: 'marshall19',
			name: '200G',
			file: '200G 1.jpg',
		},
		{
			filter: 'monotone',
			id: 'marshall20',
			name: '900APG',
			file: '900APG 1.jpg',
		},
		{
			filter: 'monotone',
			id: 'marshall21',
			name: '900G',
			file: '900G 1.jpg',
		},
		{
			filter: 'monotone',
			id: 'marshall22',
			name: '400G',
			file: '400G 1.jpg',
		},
		{
			filter: 'monotone',
			id: 'marshall23',
			name: '1115BG',
			file: '1115BG 1.jpg',
		},
		{
			filter: 'monotone',
			id: 'marshall24',
			name: '1179AG',
			file: '1179AG 1.jpg',
		},
		{
			filter: 'monotone',
			id: 'marshall25',
			name: '2706G',
			file: '2706G 1.jpg',
		},
		{
			filter: 'texture',
			id: 'marshall26',
			name: '1190BG',
			file: '1190BG 1.jpg',
		},
		{
			filter: 'texture',
			id: 'marshall27',
			name: '1176AG',
			file: '1176AG 1.jpg',
		},
		{
			filter: 'texture',
			id: 'marshall28',
			name: '400SPG',
			file: '400SPG 1.jpg',
		},
		{
			filter: 'texture',
			id: 'marshall29',
			name: '400ELM',
			file: '400ELM 1.jpg',
		},
		{
			filter: 'texture',
			id: 'marshall30',
			name: '90SPG',
			file: '90SPG 1.jpg',
		},
		{
			filter: 'texture',
			id: 'marshall31',
			name: '200POG',
			file: '200POG 1.jpg',
		},
		{
			filter: 'texture',
			id: 'marshall32',
			name: '900POG',
			file: '900POG 1.jpg',
		},
		{
			filter: 'texture',
			id: 'marshall33',
			name: '1114AG',
			file: '1114AG 1.jpg',
		},
		{
			filter: 'texture',
			id: 'marshall34',
			name: '1554ANT',
			file: '1554ANT 1.jpg',
		},
		{
			filter: 'texture',
			id: 'marshall35',
			name: '1555ANT',
			file: '1555ANT 1.jpg',
		},
		{
			filter: 'monotone',
			id: 'marshall36',
			name: '1725AG',
			file: '1725AG 1.jpg',
		},
		{
			filter: 'monotone',
			id: 'marshall37',
			name: '1757AG',
			file: '1757AG 1.jpg',
		},
		{
			filter: 'monotone',
			id: 'marshall38',
			name: '1759AG',
			file: '1759AG 1.jpg',
		},
		{
			filter: 'monotone',
			id: 'marshall39',
			name: '1763AG',
			file: '1763AG 1.jpg',
		},
		{
			filter: 'monotone',
			id: 'marshall40',
			name: '1789AG',
			file: '1789AG 1.jpg',
		},
		{
			filter: 'monotone',
			id: 'marshall41',
			name: '2709G',
			file: '2709G 1.jpg',
		},
		{
			filter: 'monotone',
			id: 'marshall42',
			name: '2712G',
			file: '2712G 1.jpg',
		},
		{
			filter: 'monotone',
			id: 'marshall43',
			name: '2715G',
			file: '2715G 1.jpg',
		},
		{
			filter: 'monotone',
			id: 'marshall44',
			name: '2718G',
			file: '2718G 1.jpg',
		},
		{
			filter: 'monotone',
			id: 'marshall45',
			name: '2745AG',
			file: '2745AG 1.jpg',
		},
		{
			filter: 'monotone',
			id: 'marshall46',
			name: '2745BG',
			file: '2745BG 1.jpg',
		},
		{
			filter: 'monotone',
			id: 'marshall47',
			name: '2745CG',
			file: '2745CG 1.jpg',
		},
		],
	tabletop: [
		{
			filter: 'monotone',
			id: 'tabletop01',
			name: 'alyuminievaya polosa 5014',
			file: 'alyuminievaya-polosa-5014 1.jpg',
		},
		{
			filter: 'monotone',
			id: 'tabletop02',
			name: 'alyuminievaya polosa 5014',
			file: 'alyuminievaya-polosa-5014-gl 1.jpg',
		},
		{
			filter: 'monotone',
			id: 'tabletop03',
			name: 'beliy 1011 gl',
			file: 'beliy-1011-gl 1.jpg',
		},
		{
			filter: 'monotone',
			id: 'tabletop04',
			name: 'beliy 1111 q',
			file: 'beliy-1111-q 1.jpg',
		},
		{
			filter: 'monotone',
			id: 'tabletop05',
			name: 'beliy 1111 s',
			file: 'beliy-1111-s 1.jpg',
		},
		{
			filter: 'monotone',
			id: 'tabletop06',
			name: 'dub souberi svetliy 7141',
			file: 'dub-souberi-svetliy-7141 1.jpg',
		},
		{
			filter: 'stones',
			id: 'tabletop07',
			name: 'alambra tyomnaya 4035',
			file: 'alambra-tyomnaya-4035 1.jpg',
		},
		{
			filter: 'stones',
			id: 'tabletop08',
			name: 'balkanskiy slanez cherniy 2333',
			file: 'balkanskiy-slanez-cherniy-2333 1.jpg',
		},
		{
			filter: 'stones',
			id: 'tabletop09',
			name: 'balkanskiy slanez rijziy 2332',
			file: 'balkanskiy-slanez-rijziy-2332 1.jpg',
		},
		{
			filter: 'stones',
			id: 'tabletop10',
			name: 'kameshki 4025',
			file: 'kameshki-4025 1.jpg',
		},
		{
			filter: 'stones',
			id: 'tabletop11',
			name: 'kantri 20471',
			file: 'kantri-2047 1.jpg',
		},
		{
			filter: 'fantasy',
			id: 'tabletop12',
			name: 'andromeda belaya 7001',
			file: 'andromeda-belaya-7001 1.jpg',
		},
		{
			filter: 'fantasy',
			id: 'tabletop13',
			name: 'andromeda chernaya 7002',
			file: 'andromeda-chernaya-7002 1.jpg',
		},
		{
			filter: 'fantasy',
			id: 'tabletop14',
			name: 'antares 4040',
			file: 'antares-4040 1.jpg',
		},
		{
			filter: 'fantasy',
			id: 'tabletop15',
			name: 'galaktika 4018',
			file: 'galaktika-4018 1.jpg',
		},
		{
			filter: 'fantasy',
			id: 'tabletop16',
			name: 'kristall barhatniy 7043',
			file: 'kristall-barhatniy-7043 1.jpg',
		},
		{
			filter: 'fantasy',
			id: 'tabletop17',
			name: 'kastillo tyomniy 4046',
			file: 'kastillo-tyomniy-4046 1.jpg',
		},
		{
			filter: 'fantasy',
			id: 'tabletop18',
			name: 'grenobl 4042',
			file: 'grenobl-4042 1.jpg',
		},
		{
			filter: 'fantasy',
			id: 'tabletop19',
			name: 'attika 4023',
			file: 'attika-4023 1.jpg',
		},
		{
			filter: 'stones',
			id: 'tabletop20',
			name: 'alambra 4026',
			file: 'alambra-4026 1.jpg',
		},
		{
			filter: 'stones',
			id: 'tabletop21',
			name: 'alambra-4026',
			file: 'alambra-4026 2.jpg',
		},
		{
			filter: 'stones',
			id: 'tabletop22',
			name: 'ardeziya 4052',
			file: 'ardeziya-4052 1.jpg',
		},
		{
			filter: 'stones',
			id: 'tabletop23',
			name: 'arvika 4075',
			file: 'arvika-4075 1.jpg',
		},
		{
			filter: 'stones',
			id: 'tabletop24',
			name: 'betao-3045',
			file: 'betao-3045 1.jpg',
		},
		{
			filter: 'stones',
			id: 'tabletop25',
			name: 'granit sardinskiy svetliy 3022',
			file: 'granit-sardinskiy-svetliy-3022 1.jpg',
		},
		{
			filter: 'stones',
			id: 'tabletop26',
			name: 'granit sardinskiy svetliy 3022 gl',
			file: 'granit-sardinskiy-svetliy-3022-gl 1.jpg',
		},
		{
			filter: 'stones',
			id: 'tabletop27',
			name: 'biser svetliy 4033',
			file: 'biser-svetliy-4033 1.jpg',
		},
		{
			filter: 'stones',
			id: 'tabletop28',
			name: 'biser svetliy 4033',
			file: 'biser-svetliy-4033 2.jpg',
		},
		{
			filter: 'woody',
			id: 'tabletop29',
			name: 'bambuk 2042',
			file: 'bambuk-2042 1.jpg',
		},
		{
			filter: 'woody',
			id: 'tabletop30',
			name: 'buk 2019',
			file: 'buk-2019 1.jpg',
		},
		{
			filter: 'woody',
			id: 'tabletop31',
			name: 'buk badenskiy 3254',
			file: 'buk-badenskiy-3254 1.jpg',
		},
		{
			filter: 'woody',
			id: 'tabletop32',
			name: 'drevesniy brus 2044',
			file: 'drevesniy-brus-2044 1.jpg',
		},
		{
			filter: 'woody',
			id: 'tabletop33',
			name: 'dub karpenter 7120',
			file: 'dub-karpenter-7120 1.jpg',
		},
		{
			filter: 'woody',
			id: 'tabletop34',
			name: 'dub souberi seriy 7144',
			file: 'dub-souberi-seriy-7144 1.jpg',
		},
		{
			filter: 'woody',
			id: 'tabletop35',
			name: 'dub souberi temniy 7142',
			file: 'dub-souberi-temniy-7142 1.jpg',
		},
		{
			filter: 'woody',
			id: 'tabletop36',
			name: 'dub vibelenniy 2022',
			file: 'dub-vibelenniy-2022 1.jpg',
		},
		{
			filter: 'woody',
			id: 'tabletop37',
			name: 'kaza strip 2016',
			file: 'kaza-strip-2016 1.jpg',
		},
		{
			filter: 'woody',
			id: 'tabletop38',
			name: 'koren vyaza 2021',
			file: 'koren-vyaza-2021 1.jpg',
		},
		{
			filter: 'woody',
			id: 'tabletop39',
			name: 'koren vyaza 2021 gl',
			file: 'koren-vyaza-2021-gl 1.jpg',
		},
		{
			filter: 'woody',
			id: 'tabletop40',
			name: 'venge 2017',
			file: 'venge-2017 1.jpg',
		},
		{
			filter: 'woody',
			id: 'tabletop41',
			name: 'venge 2017 gl',
			file: 'venge-2017-gl 1.jpg',
		},
		{
			filter: 'woody',
			id: 'tabletop42',
			name: 'vintajz 2326',
			file: 'vintajz-2326 1.jpg',
		},
		{
			filter: 'stones',
			id: 'tabletop43',
			name: 'italyanskaya mozaika 4051',
			file: 'italyanskaya-mozaika-4051 1.jpg',
		},
		{
			filter: 'stones',
			id: 'tabletop44',
			name: 'kalakatta 4030',
			file: 'kalakatta-4030 1.jpg',
		},
		{
			filter: 'stones',
			id: 'tabletop45',
			name: 'kalakatta 4030 gl',
			file: 'kalakatta-4030-gl 1.jpg',
		},
		{
			filter: 'stones',
			id: 'tabletop46',
			name: 'kastillo 4045',
			file: 'kastillo-4045 1.jpg',
		},
		{
			filter: 'stones',
			id: 'tabletop47',
			name: 'kastillo 4045 gl',
			file: 'kastillo-4045-gl 1.jpg',
		},
		{
			filter: 'fantasy',
			id: 'tabletop48',
			name: 'galiya 2946',
			file: 'galiya-2946 1.jpg',
		},
		],
	kstyle: [
		{
			filter: 'econom',
			id: 'k-style01',
			file: 'k-style01.jpg',
		},
		{
			filter: 'econom',
			id: 'k-style02',
			file: '0102k-style04.jpg',
		},
		{
			filter: 'econom',
			id: 'k-style03',
			file: 'k-style03.jpg',
		},
		{
			filter: 'econom',
			id: 'k-style04',
			file: 'k-style03.jpg',
		},
		{
			filter: 'econom',
			id: 'k-style05',
			file: 'k-style05.jpg',
		},
		{
			filter: 'econom',
			id: 'k-style06',
			file: 'k-style06.jpg',
		},
		{
			filter: 'loft',
			id: 'k-style07',
			file: '0101k-style02.jpg',
		},
		{
			filter: 'loft',
			id: 'k-style08',
			file: '0101k-style02.jpg',
		},
		{
			filter: 'loft',
			id: 'k-style09',
			file: '0101k-style02.jpg',
		},
		{
			filter: 'loft',
			id: 'k-style10',
			file: '0101k-style02.jpg',
		},
		{
			filter: 'loft',
			id: 'k-style11',
			file: '0101k-style02.jpg',
		},
		{
			filter: 'loft',
			id: 'k-style12',
			file: '0101k-style02.jpg',
		},
		{
			filter: 'classic',
			id: 'k-style13',
			file: 'classic.jpg.webp',
		},
		{
			filter: 'classic',
			id: 'k-style14',
			file: 'classic.jpg.webp',
		},
		{
			filter: 'classic',
			id: 'k-style15',
			file: 'classic.jpg.webp',
		},
		{
			filter: 'classic',
			id: 'k-style16',
			file: 'classic.jpg.webp',
		},
		{
			filter: 'classic',
			id: 'k-style17',
			file: 'classic.jpg.webp',
		},
		{
			filter: 'classic',
			id: 'k-style18',
			file: 'classic.jpg.webp',
		},
		{
			filter: 'hi-te',
			id: 'k-style19',
			file: 'kuhonnyi-garnitur-hai-tek.jpg.webp',
		},
		{
			filter: 'hi-te',
			id: 'k-style20',
			file: 'kuhonnyi-garnitur-hai-tek.jpg.webp',
		},
		{
			filter: 'hi-te',
			id: 'k-style21',
			file: 'kuhonnyi-garnitur-hai-tek.jpg.webp',
		},
		{
			filter: 'hi-te',
			id: 'k-style22',
			file: 'kuhonnyi-garnitur-hai-tek.jpg.webp',
		},
		{
			filter: 'hi-te',
			id: 'k-style23',
			file: 'kuhonnyi-garnitur-hai-tek.jpg.webp',
		},
		{
			filter: 'hi-te',
			id: 'k-style24',
			file: 'kuhonnyi-garnitur-hai-tek.jpg.webp',
		},
		{
			filter: 'mini',
			id: 'k-style25',
			file: 'minimapelsin-oranzh-15-m-12900-rub.-1.jpg.webp',
		},
		{
			filter: 'mini',
			id: 'k-style26',
			file: 'minimapelsin-oranzh-15-m-12900-rub.-1.jpg.webp',
		},
		{
			filter: 'mini',
			id: 'k-style27',
			file: 'minimapelsin-oranzh-15-m-12900-rub.-1.jpg.webp',
		},
		{
			filter: 'mini',
			id: 'k-style28',
			file: 'minimapelsin-oranzh-15-m-12900-rub.-1.jpg.webp',
		},
		{
			filter: 'mini',
			id: 'k-style29',
			file: 'minimapelsin-oranzh-15-m-12900-rub.-1.jpg.webp',
		},
		{
			filter: 'mini',
			id: 'k-style30',
			file: 'minimapelsin-oranzh-15-m-12900-rub.-1.jpg.webp',
		},
		{
			filter: 'provance',
			id: 'k-style31',
			file: 'provans-model-3489.jpg.webp',
		},
		{
			filter: 'provance',
			id: 'k-style32',
			file: 'provans-model-3489.jpg.webp',
		},
		{
			filter: 'provance',
			id: 'k-style33',
			file: 'provans-model-3489.jpg.webp',
		},
		{
			filter: 'provance',
			id: 'k-style34',
			file: 'provans-model-3489.jpg.webp',
		},
		{
			filter: 'provance',
			id: 'k-style35',
			file: 'provans-model-3489.jpg.webp',
		},
		{
			filter: 'provance',
			id: 'k-style36',
			file: 'provans-model-3489.jpg.webp',
		},
		{
			filter: 'scandinavic',
			id: 'k-style37',
			file: 'scandinavian-style-5-1.jpg.webp',
		},
		{
			filter: 'scandinavic',
			id: 'k-style38',
			file: 'scandinavian-style-5-1.jpg.webp',
		},
		{
			filter: 'scandinavic',
			id: 'k-style39',
			file: 'scandinavian-style-5-1.jpg.webp',
		},
		{
			filter: 'scandinavic',
			id: 'k-style40',
			file: 'scandinavian-style-5-1.jpg.webp',
		},
		{
			filter: 'scandinavic',
			id: 'k-style41',
			file: 'scandinavian-style-5-1.jpg.webp',
		},
		{
			filter: 'scandinavic',
			id: 'k-style42',
			file: 'scandinavian-style-5-1.jpg.webp',
		},
		{
			filter: 'little',
			id: 'k-style43',
			file: 'small-1.jpg.webp',
		},
		{
			filter: 'little',
			id: 'k-style44',
			file: 'small-1.jpg.webp',
		},
		{
			filter: 'little',
			id: 'k-style45',
			file: 'small-1.jpg.webp',
		},
		{
			filter: 'little',
			id: 'k-style46',
			file: 'small-1.jpg.webp',
		},
		{
			filter: 'little',
			id: 'k-style47',
			file: 'small-1.jpg.webp',
		},
		{
			filter: 'little',
			id: 'k-style48',
			file: 'small-1.jpg.webp',
		},
		],
	photoprn: [
		{
			filter: 'city',
			id: 'photoprn01',
			name: 'города',
			file: 'img/photoprint/s002.jpg',
		},
		{
			filter: 'city',
			id: 'photoprn02',
			name: 'города',
			file: 'img/photoprint/s002.jpg',
		},
		{
			filter: 'city',
			id: 'photoprn03',
			name: 'города',
			file: 'img/photoprint/s002.jpg',
		},
		{
			filter: 'city',
			id: 'photoprn04',
			name: 'города',
			file: 'img/photoprint/s002.jpg',
		},
		{
			filter: 'city',
			id: 'photoprn05',
			name: 'города',
			file: 'img/photoprint/s002.jpg',
		},
		{
			filter: 'city',
			id: 'photoprn06',
			name: 'города',
			file: 'img/photoprint/s002.jpg',
		},
		{
			filter: 'city',
			id: 'photoprn07',
			name: 'города',
			file: 'img/photoprint/s002.jpg',
		},
		{
			filter: 'city',
			id: 'photoprn08',
			name: 'города',
			file: 'img/photoprint/s002.jpg',
		},
		{
			filter: 'city',
			id: 'photoprn09',
			name: 'города',
			file: 'img/photoprint/s002.jpg',
		},
		{
			filter: 'fruits',
			id: 'photoprn10',
			name: 'Клубника',
			file: 'img/photoprint/m004.jpg',
		},
		{
			filter: 'fruits',
			id: 'photoprn11',
			name: 'Клубника',
			file: 'img/photoprint/m004.jpg',
		},
		{
			filter: 'fruits',
			id: 'photoprn12',
			name: 'Клубника',
			file: 'img/photoprint/m004.jpg',
		},
		{
			filter: 'fruits',
			id: 'photoprn13',
			name: 'Клубника',
			file: 'img/photoprint/m004.jpg',
		},
		{
			filter: 'fruits',
			id: 'photoprn14',
			name: 'Клубника',
			file: 'img/photoprint/m004.jpg',
		},
		{
			filter: 'fruits',
			id: 'photoprn15',
			name: 'Клубника',
			file: 'img/photoprint/m004.jpg',
		},
		{
			filter: 'fruits',
			id: 'photoprn16',
			name: 'Клубника',
			file: 'img/photoprint/m004.jpg',
		},
		{
			filter: 'fruits',
			id: 'photoprn17',
			name: 'Клубника',
			file: 'img/photoprint/m004.jpg',
		},
		{
			filter: 'fruits',
			id: 'photoprn18',
			name: 'Клубника',
			file: 'img/photoprint/m004.jpg',
		},
		{
			filter: 'fruits',
			id: 'photoprn19',
			name: 'Клубника',
			file: 'img/photoprint/m004.jpg',
		},
		{
			filter: 'flowers',
			id: 'photoprn20',
			name: 'Цветы',
			file: 'img/photoprint/f024.jpg',
		},
		{
			filter: 'flowers',
			id: 'photoprn21',
			name: 'Цветы',
			file: 'img/photoprint/f024.jpg',
		},
		{
			filter: 'flowers',
			id: 'photoprn22',
			name: 'Цветы',
			file: 'img/photoprint/f024.jpg',
		},
		{
			filter: 'flowers',
			id: 'photoprn23',
			name: 'Цветы',
			file: 'img/photoprint/f024.jpg',
		},
		{
			filter: 'flowers',
			id: 'photoprn24',
			name: 'Цветы',
			file: 'img/photoprint/f024.jpg',
		},
		{
			filter: 'flowers',
			id: 'photoprn25',
			name: 'Цветы',
			file: 'img/photoprint/f024.jpg',
		},
		{
			filter: 'flowers',
			id: 'photoprn26',
			name: 'Цветы',
			file: 'img/photoprint/f024.jpg',
		},
		{
			filter: 'flowers',
			id: 'photoprn27',
			name: 'Цветы',
			file: 'img/photoprint/f024.jpg',
		},
		{
			filter: 'flowers',
			id: 'photoprn28',
			name: 'Цветы',
			file: 'img/photoprint/f024.jpg',
		},
		{
			filter: 'flowers',
			id: 'photoprn29',
			name: 'Цветы',
			file: 'img/photoprint/f024.jpg',
		},
		{
			filter: 'other',
			id: 'photoprn30',
			name: 'Прочее',
			file: 'img/photoprint/f045.jpg',
		},
		{
			filter: 'other',
			id: 'photoprn31',
			name: 'Прочее',
			file: 'img/photoprint/f045.jpg',
		},
		{
			filter: 'other',
			id: 'photoprn32',
			name: 'Прочее',
			file: 'img/photoprint/f045.jpg',
		},
		{
			filter: 'other',
			id: 'photoprn33',
			name: 'Прочее',
			file: 'img/photoprint/f045.jpg',
		},
		{
			filter: 'other',
			id: 'photoprn34',
			name: 'Прочее',
			file: 'img/photoprint/f045.jpg',
		},
		{
			filter: 'other',
			id: 'photoprn35',
			name: 'Прочее',
			file: 'img/photoprint/f045.jpg',
		},
		{
			filter: 'other',
			id: 'photoprn36',
			name: 'Прочее',
			file: 'img/photoprint/f045.jpg',
		},
		{
			filter: 'other',
			id: 'photoprn37',
			name: 'Прочее',
			file: 'img/photoprint/f045.jpg',
		},
		{
			filter: 'other',
			id: 'photoprn38',
			name: 'Прочее',
			file: 'img/photoprint/f045.jpg',
		},
		{
			filter: 'other',
			id: 'photoprn39',
			name: 'Прочее',
			file: 'img/photoprint/f045.jpg',
		},
		{
			filter: 'nature',
			id: 'photoprn40',
			name: 'Природа',
			file: 'img/photoprint/n018 1.jpg',
		},
		{
			filter: 'nature',
			id: 'photoprn41',
			name: 'Природа',
			file: 'img/photoprint/n021 1.jpg',
		},
		{
			filter: 'nature',
			id: 'photoprn42',
			name: 'Природа',
			file: 'img/photoprint/n022 1.jpg',
		},
		{
			filter: 'nature',
			id: 'photoprn43',
			name: 'Природа',
			file: 'img/photoprint/n023 1.jpg',
		},
		{
			filter: 'nature',
			id: 'photoprn44',
			name: 'Природа',
			file: 'img/photoprint/n024 1.jpg',
		},
		{
			filter: 'nature',
			id: 'photoprn45',
			name: 'Природа',
			file: 'img/photoprint/n029 1.jpg',
		},
		{
			filter: 'nature',
			id: 'photoprn46',
			name: 'Природа',
			file: 'img/photoprint/n037 1.jpg',
		},
		{
			filter: 'nature',
			id: 'photoprn47',
			name: 'Природа',
			file: 'img/photoprint/n039 1.jpg',
		},
		{
			filter: 'nature',
			id: 'photoprn48',
			name: 'Природа',
			file: 'img/photoprint/n047 1.jpg',
		},
		{
			filter: 'nature',
			id: 'photoprn49',
			name: 'Природа',
			file: 'img/photoprint/n047 1.jpg',
		},
		],
}
